
//主菜单参数
var mainMenuIndex = 0; 
//maxID:37
var menuData = [
	//{ pid: 0, id: 1, text: "我的桌面", page: "myDesktop.html" },
    { pid: 0, id: 1, text: "我的桌面", page: "myDesktop.html" },
		{ pid: 1, id: 101, text: "待办任务", page: "myDesktop.html" },
		{ pid: 1, id: 102, text: "已办任务", page: "myDesktop.html" },
		{ pid: 1, id: 103, text: "公文查收", page: "myDesktop.html" },
			{ pid: 103, id: 10301, text: "公文拟稿", page: "myDesktop.html" },
			{ pid: 103, id: 10302, text: "公文查询", page: "myDesktop.html" },
		{ pid: 1, id: 104, text: "通知公告", page: "myDesktop.html" },
		{ pid: 1, id: 105, text: "信息报送", page: "myDesktop.html" },
		{ pid: 1, id: 106, text: "我的设置", page: "myDesktop.html" },

	{ pid: 0, id: 2, text: "一镇一档", page: "Organization.html" },
	    { pid: 2, id: 9, text: "宁波市", page: "" , type:1},
	        { pid: 9, id: 10, text: "海曙区", page: "Organization.html" },
	            { pid: 10, id: 24, text: "集士港", page: "myDesktop.html" },
	            { pid: 10, id: 25, text: "章水", page: "Organization.html" },
	            { pid: 10, id: 26, text: "龙观乡", page: "Organization.html" },
	            { pid: 10, id: 27, text: "石碶", page: "Organization.html" },
	            { pid: 10, id: 28, text: "高桥", page: "Organization.html" },
	            { pid: 10, id: 29, text: "鄞江", page: "Organization.html" },
	            { pid: 10, id: 30, text: "横街", page: "Organization.html" },
	            { pid: 10, id: 31, text: "洞桥", page: "Organization.html" },
	            { pid: 10, id: 32, text: "古林", page: "Organization.html" },
	        { pid: 9, id: 11, text: "江北区", page: "Organization.html" },
	        { pid: 9, id: 12, text: "镇海区", page: "Organization.html" },
	        { pid: 9, id: 13, text: "北仑区", page: "Organization.html" },
	        { pid: 9, id: 14, text: "鄞州区", page: "Organization.html" },
	        { pid: 9, id: 15, text: "奉化区", page: "Organization.html" },
	        { pid: 9, id: 16, text: "余姚市", page: "Organization.html" },
	        { pid: 9, id: 17, text: "慈溪市", page: "Organization.html" },
	        { pid: 9, id: 18, text: "宁海县", page: "Organization.html" },
	        { pid: 9, id: 19, text: "象山县", page: "Organization.html" },
	        { pid: 9, id: 20, text: "东钱湖", page: "Organization.html" },
	        { pid: 9, id: 21, text: "大榭", page: "Organization.html" },
	        { pid: 9, id: 22, text: "高新区", page: "Organization.html" },
	        { pid: 9, id: 23, text: "杭州湾", page: "Organization.html" },

	{ pid: 0, id: 3, text: "日常监管", page: "Streetscape.html"},
		{ pid: 3, id: 301, text: "视频监控", page: "Streetscape.html" },
		{ pid: 3, id: 302, text: "日常巡查", page: "Streetscape_InitiatingTask.html" },
		
	{ pid: 0, id: 4, text: "项目管理", page: "projectAdmin.html"},
		{ pid: 4, id: 401, text: "全部项目", page: "projectAdmin.html" },
		{ pid: 4, id: 402, text: "在建项目", page: "projectAdmin.html" },
		{ pid: 4, id: 403, text: "已建项目", page: "projectAdmin.html" },
		
		
	{ pid: 0, id: 5, text: "预 考 核", page: "Assess.html"},
		{ pid: 5, id: 501, text: "预 考 核", page: "Assess.html"},
	{ pid: 0, id: 6, text: "专题数据", page: "ThematicData.html"},
		{ pid: 6, id: 601, text: "图层", page: "ThematicData.html",type:1,haveCheckbox:1},
			{ pid: 601, id: 60101, text: "环境整治专题数据", page: "ThematicData.html",haveCheckbox:1},
				{ pid: 60101, id: 6010101, text: "规划专题", page: "ThematicData.html",haveCheckbox:1},
					{ pid: 6010101, id: 601010101, text: "规划专题", page: "ThematicData.html",haveCheckbox:1},
					{ pid: 6010101, id: 601010102, text: "规划专题", page: "ThematicData.html",haveCheckbox:1},
				{ pid: 60101, id: 6010102, text: "乡镇特色专题", page: "ThematicData.html",haveCheckbox:1},
				{ pid: 60101, id: 6010103, text: "环卫设施专题", page: "ThematicData.html",haveCheckbox:1},
				{ pid: 60101, id: 6010104, text: "“五水共治”专题", page: "ThematicData.html",haveCheckbox:1},
				{ pid: 60101, id: 6010105, text: "农贸市场专题", page: "ThematicData.html",haveCheckbox:1},
					{ pid: 6010105, id: 601010501, text: "农贸市场", page: "ThematicData.html",haveCheckbox:1},
				{ pid: 60101, id: 6010106, text: "桥下空间数据", page: "ThematicData.html",haveCheckbox:1},
				{ pid: 60101, id: 6010107, text: "绿地绿化专题", page: "ThematicData.html",haveCheckbox:1},
				{ pid: 60101, id: 6010108, text: "无人机航拍视频", page: "ThematicData.html",haveCheckbox:1},
	
	{ pid: 0, id: 7, text: "统计分析", page: "projectAdmin.html"},
	{ pid: 0, id: 8, text: "后台管理", page: "projectManage.html" },
		{ pid: 8, id: 801, text: "项目管理", page: "projectManage.html" },
		{ pid: 8, id: 802, text: "组织机构管理", page: "projectManage.html" },

] 